apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-tag
  labels:
    app: golang-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-tag
  template:
    metadata:
      labels:
        app: golang-tag
    spec:
      containers:
      - name: golang-tag
        image: myrachanto/single:0.0.2-feature.0
        ports:
          - containerPort: 2200
---
apiVersion: v1
kind: Service
metadata:
  name: golang-tag-service
spec:
  type: ClusterIP
  selector:
    app: golang-tag
  ports:
     - port: 2200
       targetPort: 2200